name: Rollback via Ansistrano

on:
  workflow_call:
    secrets:
      SSH_PRIVATE_KEY:
        description: 'SSH private key'
        required: true

permissions:
  contents: read

jobs:
  rollback:
    name: rollback via Ansistrano
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Get PiP Cache Directory
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"

      - name: Cache PiP dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-ansible

      - name: Cache Python environment
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-ansible

      - name: Install Ansible and it's dependencies
        run: pip install --upgrade --upgrade-strategy eager ansible

      - name: Install Ansistrano
        run: ansible-galaxy install --force ansistrano.deploy ansistrano.rollback

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "${{  secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Rollback
        run: ansible-playbook -i .ansistrano/hosts.yml .ansistrano/rollback.yml -v
        env:
          # Force color output.
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
