name: Deploy via Ansistrano

on:
  workflow_call:
    inputs:
      deploy_target:
        description: 'What version of the repository to check out. This can be the full 40-character SHA-1 hash, the literal string HEAD, a branch name, or a tag name'
        required: true
        default: 'main'
        type: string
    secrets:
      SSH_PRIVATE_KEY:
        description: 'SSH private key'
        required: true

permissions:
  contents: read

jobs:
  deploy:
    name: deploy via Ansistrano
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Get PiP Cache Directory
        id: pip-cache
        run: |
          echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT

      - name: Cache PiP dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-ansible

      - name: Cache Python environment
        uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-ansible

      - name: Install Ansible and it's dependencies
        run: pip install --upgrade --upgrade-strategy eager ansible

      - name: Install Ansistrano
        run: ansible-galaxy install --force ansistrano.deploy ansistrano.rollback

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "${{  secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Deploy
        run: ansible-playbook -i .ansistrano/hosts.yml .ansistrano/deploy.yml --extra-vars "ansistrano_git_branch=${{ inputs.deploy_target }}" -v
        env:
          # Force color output.
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
