name: Automerge a PR
on:
  workflow_call:
    inputs:
      pull_request_url:
        required: false
        type: string
        default: ${{ github.event.pull_request.html_url }}

permissions:
  pull-requests: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Enable automerge
        run: gh pr merge --auto --squash "${{ inputs.pull_request_url }}"
        env:
          GITHUB_TOKEN: "${{ github.token }}"
