name: Composer lock diff
on:
  workflow_call:
    inputs:
      head_ref:
        required: false
        type: string
        default: ${{ github.head_ref }}
      base_ref:
        required: false
        type: string
        default: ${{ github.base_ref }}
      pull_request_number:
        required: false
        type: string
        default: ${{ github.event.pull_request.number }}
    secrets:
      PHP_VERSION:
        description: 'PHP version to use'
      COMPOSER_VERSION:
        description: 'Composer version to use'

permissions:
  contents: read
  pull-requests: write

jobs:
  composer_diff:
    name: composer lock diff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.head_ref }}
          # Required to make it possible to compare with PR base branch.
          fetch-depth: 0

      - name: Get the base (old) branch latest commit SHA
        id: base_sha
        run: |
          git fetch origin
          echo "::set-output name=base_sha::$(git rev-parse origin/${{ inputs.base_ref }})"

      - name: Rebase current branch (avoid outdated diff results)
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git fetch origin
          git rebase origin/${{ inputs.base_ref }}

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ secrets.PHP_VERSION }}
          tools: composer:${{ secrets.COMPOSER_VERSION }}

      - name: Install and configure ion-bazan/composer_diff
        run: |
          composer global config allow-plugins.ion-bazan/composer-diff true
          composer global require ion-bazan/composer-diff

      - name: Run composer lock diff
        id: composer_diff
        run: |
          OUTPUT=$(composer diff --base ${{ steps.base_sha.outputs.base_sha }} --with-links --with-platform --no-ansi)

          # Escape multiline output, see https://renehernandez.io/snippets/multiline-strings-as-a-job-output-in-github-actions/
          OUTPUT="${OUTPUT//'%'/'%25'}"
          OUTPUT="${OUTPUT//$'\n'/'%0A'}"
          OUTPUT="${OUTPUT//$'\r'/'%0D'}"

          echo -n "::set-output name=composer_diff::$OUTPUT"

      - name: Create/update comment when diff is not empty
        uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ steps.composer_diff.outputs.composer_diff != '' }}
        with:
          number: ${{ inputs.pull_request_number }}
          header: composer_diff
          hide_and_recreate: true
          hide_classify: "OUTDATED"
          message: |
            ${{ steps.composer_diff.outputs.composer_diff }}

      - name: Hide comment when diff is empty
        uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ steps.composer_diff.outputs.composer_diff == '' }}
        with:
          number: ${{ inputs.pull_request_number }}
          header: composer_diff
          hide: true
          hide_classify: "OUTDATED"
