name: Composer lock diff
on:
  workflow_call:
    inputs:
      head:
        required: false
        type: string
        default: ${{ github.head_ref }}
      base:
        required: false
        type: string
        default: ${{ github.base_ref }}
      pr_number:
        required: false
        type: string
        default: ${{ github.event.pull_request.number }}
    secrets:
      PHP_VERSION:
      COMPOSER_VERSION:

permissions:
  contents: read
  pull-requests: write

jobs:
  composer-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.head }}
          # Required to make it possible to compare with PR base branch.
          fetch-depth: 0

      - name: Get the base (old) branch latest commit SHA
        id: base-sha
        run: |
          git fetch origin
          echo "::set-output name=base_sha::$(git rev-parse origin/${{ inputs.base }})"

      - name: Rebase current branch (avoid outdated diff results)
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git fetch origin
          git rebase origin/${{ inputs.base }}

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ secrets.PHP_VERSION }}
          tools: composer:${{ secrets.COMPOSER_VERSION }}

      - name: Install and configure ion-bazan/composer-diff
        run: |
          composer global config allow-plugins.ion-bazan/composer-diff true
          composer global require ion-bazan/composer-diff

      - name: Run composer lock diff
        id: composer_diff
        run: |
          OUTPUT=$(composer diff --base ${{ steps.base-sha.outputs.base_sha }} --with-links --with-platform --strict --no-ansi)
          EXIT_CODE=$?

          echo -n "::set-output name=composer_diff::$OUTPUT"
          echo "::set-output name=composer_diff_exit_code::$EXIT_CODE"

      - uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ steps.composer_diff.outputs.composer_diff_exit_code > 1 }}
        with:
          number: ${{ inputs.pr_number }}
          header: composer-diff
          hide_and_recreate: true
          hide_classify: "OUTDATED"
          message: |
            ${{ steps.composer_diff.outputs.composer_diff }}
