name: Composer lock diff
on:
  workflow_call:
    inputs:
      php_version:
        required: true
        type: string
      composer_version:
        required: true
        type: string
      head_ref:
        required: false
        type: string
        default: ${{ github.head_ref }}
      base_ref:
        required: false
        type: string
        default: ${{ github.base_ref }}
      pull_request_number:
        required: false
        type: string
        default: ${{ github.event.pull_request.number }}

permissions:
  contents: read
  pull-requests: write

jobs:
  composer_diff_check:
    name: composer lock diff check
    runs-on: ubuntu-latest
    outputs:
      exit-code: ${{ steps.composer_lock_exists.outputs.exit-code }}
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Required to make it possible to compare with PR base branch.
          fetch-depth: 0

      - name: Check if composer.lock exists both for the base and head
        id: composer_lock_exists
        run: |
          # Checkout both base and head branches, so check can be performed.
          git checkout ${{ inputs.base_ref }}
          git checkout ${{ inputs.head_ref }}
          git rebase ${{ inputs.base_ref }}
          git show ${{ inputs.base_ref }}:composer.lock > /dev/null 2>&1 && git show ${{ inputs.head_ref }}:composer.lock > /dev/null 2>&1
          echo "exit-code=$?" >> $GITHUB_OUTPUT

  composer_diff:
    name: composer lock diff
    needs: composer_diff_check
    if: needs.composer_diff_check.outputs.exit-code == '0'
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Required to make it possible to compare with PR base branch.
          fetch-depth: 0

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ inputs.php_version }}
          tools: composer:${{ inputs.composer_version }}

      - name: Install and configure ion-bazan/composer_diff
        run: |
          composer global config allow-plugins.ion-bazan/composer-diff true
          composer global require ion-bazan/composer-diff

      - name: Run composer lock diff
        id: composer_diff
        run: |
          # Checkout both base and head branches, so check can be performed.
          git checkout ${{ inputs.base_ref }}
          git checkout ${{ inputs.head_ref }}
          git rebase ${{ inputs.base_ref }}

          # Generate a random delimiter to separate the output from the rest of the workflow.
          DELIMETER="$(openssl rand -hex 8)"

          OUTPUT=$(composer diff --base ${{ inputs.base_ref }} --target ${{ inputs.head_ref }} --with-links --with-platform --no-ansi)

          echo "composer_diff<<$DELIMETER" >> $GITHUB_OUTPUT
          echo "$OUTPUT" >> $GITHUB_OUTPUT
          echo "$DELIMETER" >> $GITHUB_OUTPUT

      - name: Create/update comment when diff is not empty
        uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ steps.composer_diff.outputs.composer_diff != '' }}
        with:
          number: ${{ inputs.pull_request_number }}
          header: composer_diff
          message: |
            ${{ steps.composer_diff.outputs.composer_diff }}

      - name: Hide comment when diff is empty
        uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ steps.composer_diff.outputs.composer_diff == '' }}
        with:
          number: ${{ inputs.pull_request_number }}
          header: composer_diff
          delete: true
