name: Dependabot metadata
on:
  workflow_call:
    outputs:
      dependency-name:
        description: Dependency name being updated
        value: ${{ jobs.metadata.outputs.dependency-name }}
      package-ecosystem:
        description: Package ecosystem being used
        value: ${{ jobs.metadata.outputs.package-ecosystem }}
      update-type:
        description: Dependency name being updated
        value: ${{ jobs.metadata.outputs.update-type }}

permissions:
  contents: read
  pull-requests: read

jobs:
  metadata:
    runs-on: ubuntu-latest
    outputs:
      dependency-name: ${{ steps.dependabot_dependency_name.outputs.dependency-name }}
      package-ecosystem: ${{ steps.dependabot_fetch_metadata.outputs.package-ecosystem }}
      update-type: ${{ steps.dependabot_fetch_metadata.outputs.update-type }}
    steps:
      - name: Fetch Dependabot metedata
        id: dependabot_fetch_metadata
        uses: dependabot/fetch-metadata@v1

      - name: Get main dependency name
        id: dependabot_dependency_name
        run: |
          echo "dependency-name=$(echo '${{ steps.dependabot_fetch_metadata.outputs.dependency-names }}' | cut -d',' -f1)" >> $GITHUB_OUTPUT
