# Dependabot does not run Composer scripts (and by coincedence also plugins).
# This is a major issue making Dependabot useless. This GA workflow fixes that
# by "redoing" the updates with scripts and plugins enabled.

name: Dependabot Workflow
on:
  workflow_call:
    inputs:
      php_version:
        required: true
        type: string
      composer_version:
        required: true
        type: string
      head_ref:
        required: false
        type: string
        default: ${{ github.head_ref }}
      base_ref:
        required: false
        type: string
        default: ${{ github.base_ref }}
      web_root:
        required: false
        type: string
        default: docroot
      pull_request_number:
        required: false
        type: string
        default: ${{ github.event.pull_request.number }}
      pull_request_url:
        required: false
        type: string
        default: ${{ github.event.pull_request.html_url }}
    secrets:
      COMPOSER_AUTH:
        description: 'Composer auth data'
        required: false

permissions:
  contents: write
  pull-requests: write

jobs:
  metadata:
    name: dependabot
    if: ${{ startsWith(inputs.head_ref, 'dependabot') }}
    uses: lembergsolutions/automation/.github/workflows/dependabot-metadata.yml@2.x

  composer:
    name: dependabot
    if: ${{ needs.metadata.outputs.package-ecosystem == 'composer' }}
    needs: metadata
    uses: lembergsolutions/automation/.github/workflows/dependabot-composer.yml@2.x
    with:
      php_version: ${{ inputs.php_version }}
      composer_version: ${{ inputs.composer_version }}
      dependency_name: ${{ needs.metadata.outputs.dependency-name }}
      head_ref: ${{ inputs.head_ref }}
      base_ref: ${{ inputs.head_ref }}
      web_root: ${{ inputs.web_root }}
    secrets:
      COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}

  composer-lock-diff:
    name: dependabot
    if: ${{ startsWith(inputs.head_ref, 'dependabot') }}
    needs: composer
    uses: lembergsolutions/automation/.github/workflows/composer-lock-diff.yml@2.x
    with:
      php_version: ${{ inputs.php_version }}
      composer_version: ${{ inputs.composer_version }}
      head_ref: ${{ inputs.head_ref }}
      base_ref: ${{ inputs.head_ref }}
      pull_request_number: ${{ inputs.pull_request_number }}

  automerge:
    name: dependabot
    # Automerge minor/patch updates only coming from dependabot branches into
    # any branch except main.
    if: ${{ startsWith(inputs.head_ref, 'dependabot') && inputs.base_ref != 'main' && (needs.metadata.outputs.update-type == 'version-update:semver-minor' || needs.metadata.outputs.update-type == 'version-update:semver-patch') }}
    needs: composer-lock-diff
    uses: lembergsolutions/automation/.github/workflows/automerge.yml@2.x
    with:
      pull_request_url: ${{ inputs.pull_request_url }}
