name: Dependabot metadata
on:
  workflow_call:
    outputs:
      package_manager:
        description: Package manager being used
        value: ${{ jobs.metadata.outputs.package_manager }}
      dependency_name:
        description: Dependency name being updated
        value: ${{ jobs.metadata.outputs.dependency_name }}

permissions:
  contents: read

jobs:
  metadata:
    runs-on: ubuntu-latest
    outputs:
      package_manager: ${{ steps.metadata_pm.outputs.package_manager }}
      dependency_name: ${{ steps.metadata_dm.outputs.dependency_name }}
    steps:
      - name: Get package ecosystem from the Dependabot branch name
        id: metadata_pm
        run: |
          echo "::set-output name=package_manager::$(awk -F/ '{print $2}' <<< '${{ github.head_ref }}')"
      - name: Get dependency name from the Dependabot branch name
        id: metadata_dm
        run: |
          echo "::set-output name=dependency_name::$(grep -oP '/\K([a-zA-Z_-]+/[a-zA-Z_-]+)(?=-\d+)' <<< '${{ github.head_ref }}')"
