name: Dependabot Composer
on:
  workflow_call:
    inputs:
      head_ref:
        required: false
        type: string
        default: ${{ github.head_ref }}
      base_ref:
        required: false
        type: string
        default: ${{ github.base_ref }}
      dependency_name:
        required: true
        type: string
    secrets:
      PHP_VERSION:
        description: 'PHP version to use'
      COMPOSER_VERSION:
        description: 'Composer version to use'
      COMPOSER_AUTH:
        description: 'Composer auth data'
        required: false

permissions:
  contents: write
  pull-requests: write

jobs:
  composer:
    name: amend composer updates
    runs-on: ubuntu-latest
    env:
      COMPOSER_AUTH: '${{ secrets.COMPOSER_AUTH }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout to the corresponding branch
        run: |
          git fetch origin ${{ inputs.head_ref }}
          git checkout --force ${{ inputs.head_ref }}

      - name: Restore composer.json & composer.lock to the previous version
        run: |
          git restore -s origin/${{ inputs.base_ref }} composer.json composer.lock

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ secrets.PHP_VERSION }}
          tools: composer:${{ secrets.COMPOSER_VERSION }}

      - name: Get Composer config
        id: composer_config
        run: |
          echo "::set-output name=cache_dir::$(composer config cache-files-dir)"
          echo "::set-output name=bin-dir::$(composer config bin-dir )"

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer_config.outputs.cache_dir }}
          key: php-${{ secrets.PHP_VERSION }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: php-${{ secrets.PHP_VERSION }}-

      - name: Build the codebase
        run: |
          composer install --no-interaction --no-progress --optimize-autoloader --prefer-dist

      - name: Get Drupal core major version
        id: drupal_version
        run: |
          echo "::set-output name=core_version::$(./vendor/bin/drush status --format=json | jq '."drupal-version" | split(".")[0] | tonumber')"

      - name: Start MySQL service & create DB
        if: ${{ steps.drupal_version.outputs.core_version != 7 }}
        run: |
          sudo systemctl start mysql.service
          sudo mysql -proot -e "CREATE USER drupal@localhost IDENTIFIED BY 'drupal'; GRANT ALL ON *.* TO drupal@localhost; FLUSH PRIVILEGES;"
          sudo mysql -proot -e 'CREATE DATABASE drupal;'

      - name: Install the project from a mini dump & import configuration
        if: ${{ steps.drupal_version.outputs.core_version != 7 }}
        run: |
          cd ./docroot
          php ./core/scripts/db-tools.php import ../.ci/dump.php.gz
          cd -
          ./vendor/bin/drush cache:rebuild
          ./vendor/bin/drush updatedb --yes
          ./vendor/bin/drush config:import --yes

      - name: Restore composer.json to the latest version by Dependabot
        run: |
          git restore composer.json

      - name: Update drupal/core (and friends) (with Composer plugins and scripts enabled)
        if: ${{ startsWith(inputs.dependency_name, 'drupal/core') }}
        run: |
          composer update "drupal/core-*" --with-all-dependencies --no-interaction

      - name: Update other packages (with Composer plugins and scripts enabled)
        if: ${{ !startsWith(inputs.dependency_name, 'drupal/core') }}
        run: |
          composer update ${{ inputs.dependency_name }} --with-all-dependencies --no-interaction

      - name: Update the DB & export the configuration
        if: ${{ steps.drupal_version.outputs.core_version != 7 }}
        run: |
          ./vendor/bin/drush cache:rebuild
          ./vendor/bin/drush updatedb --yes
          ./vendor/bin/drush config:export --yes

      - name: Post-update drupal/webform
        if: ${{ inputs.dependency_name == 'drupal/webform' && steps.drupal_version.outputs.core_version != 7 }}
        run: |
          ./vendor/bin/drush webform:composer:update
          WEBFORM_PACKAGES=$(./vendor/bin/drush webform:libraries:composer | jq -r '[.repositories[].package.name] | join(" ")')
          composer update $WEBFORM_PACKAGES

      - name: Commit the result & push update to the corresponding branch
        run: |
          git add .
          if [ -z "$(git status --porcelain)" ]; then
            exit 0
          fi
          # Get username & email from the previous commit (dependabot's)
          git config --local user.email "$(git log --format='%ae' HEAD^!)"
          git config --local user.name "$(git log --format='%an' HEAD^!)"
          # Commit without a message.
          git commit --allow-empty-message -nm ""
          git push origin ${{ inputs.head_ref }} --force
