name: Dependabot metadata
on:
  workflow_call:
    outputs:
      dependency-name:
        description: Dependency name being updated
        value: ${{ jobs.metadata.outputs.dependency-name }}
      package-ecosystem:
        description: Package ecosystem being used
        value: ${{ jobs.metadata.outputs.package-ecosystem }}
      update-type:
        description: Dependency name being updated
        value: ${{ jobs.metadata.outputs.update-type }}

permissions:
  contents: read
  pull-requests: read

jobs:
  metadata:
    runs-on: ubuntu-latest
    outputs:
      dependency-name: ${{ steps.dependabot_dependency_name.outputs.dependency-name }}
      package-ecosystem: ${{ steps.dependabot_package_ecosystem.outputs.package-ecosystem }}
      update-type: ${{ steps.dependabot_update_type.outputs.update-type }}
    steps:
      - name: Get package ecosystem from the Dependabot branch name
        id: dependabot_package_ecosystem
        run: |
          echo "package-ecosystem=$(awk -F/ '{print $2}' <<< '${{ github.head_ref }}')" >> $GITHUB_OUTPUT

      - name: Get dependency name from the Dependabot branch name
        id: dependabot_dependency_name
        run: |
          echo "dependency-name=$(grep -oP '/\K([a-zA-Z_-]+/[a-zA-Z_-]+)(?=-\d+)' <<< '${{ github.head_ref }}')" >> $GITHUB_OUTPUT

      - name: Get Dependabot update type
        id: dependabot_update_type
        if: ${{ github.actor == 'dependabot[bot]' }}
        uses: dependabot/fetch-metadata@v1
