name: PHPCS
on:
  workflow_call:
    inputs:
      php_version:
        required: true
        type: string
      composer_version:
        required: true
        type: string
      head_ref:
        required: false
        type: string
        default: ${{ github.head_ref }}

permissions:
  contents: read

jobs:
  phpcs:
    name: composer
    runs-on: ubuntu-latest
    env:
      COMPOSER_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.head_ref }}

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ inputs.php_version }}
          tools: composer:${{ inputs.composer_version }}, composer-normalize

      - name: Get Composer config
        id: composer_config
        run: |
          echo "cache_dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer_config.outputs.cache_dir }}
          key: php-${{ inputs.php_version }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: php-${{ inputs.php_version }}-

      - name: Validate composer
        run: |
          composer validate --no-check-all --strict

      - name: Build the codebase
        run: |
          composer install --no-interaction --no-progress --optimize-autoloader --prefer-dist

      - name: Normalize composer
        run: |
          composer config allow-plugins.ergebnis/composer-normalize true
          composer normalize --dry-run