name: Backup the main brach of a project on platform.sh
on:
  workflow_call:
    inputs:
      platformsh_project_id:
        required: true
        type: string
      platformsh_main_branch:
        required: false
        type: string
        default: main
    secrets:
      PLATFORMSH_CLI_TOKEN:
        description: 'Platform.sh CLI token'

jobs:
  backup:
    runs-on: ubuntu-latest
    env:
      PLATFORMSH_CLI_TOKEN: ${{ secrets.PLATFORMSH_CLI_TOKEN }}
    steps:
      - name: Install Platform.sh CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/platformsh/cli/main/installer.sh | bash

      - name: Backup the project
        run: |
          platform backup:create --project ${{ inputs.platformsh_project_id }} --environment ${{ inputs.platformsh_main_branch }} --yes --no-wait
