name: Backup the main brach of a project on platform.sh
on:
  workflow_call:
    inputs:
      php_version:
        required: true
        type: string
      composer_version:
        required: true
        type: string
      platformsh_project_id:
        required: true
        type: string
      platformsh_main_branch:
        required: false
        type: string
        default: main
    secrets:
      PLATFORMSH_CLI_TOKEN:
        description: 'Platform.sh CLI token'

jobs:
  backup:
    runs-on: ubuntu-latest
    env:
      PLATFORMSH_CLI_TOKEN: ${{ secrets.PLATFORMSH_CLI_TOKEN }}
    steps:
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ inputs.php_version }}
          tools: composer:${{ inputs.composer_version }}

      - name: Install Platform.sh CLI
        run: |
          curl -fsS https://platform.sh/cli/installer | php

      - name: Backup the project
        run: |
          ~/.platformsh/bin/platform backup:create --project ${{ inputs.platformsh_project_id }} --environment ${{ inputs.platformsh_main_branch }} --yes --no-wait
