name: Rebase a dependent branch
on:
  workflow_call:
    inputs:
      main_branch:
        required: false
        type: string
        default: main
      dependent_branch:
        required: true
        type: string

permissions:
  contents: write

jobs:
  rebase:
    name: Checkout branch ${{ inputs.dependent_branch }}
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.dependent_branch }}
          # Required to make it possible to rebase with the main branch.
          fetch-depth: 0

      - name: Config git & fetch repository
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git fetch origin

      - name: Rebase ${{ inputs.dependent_branch }} branch (aggressive strategy)
        if: ${{ github.event.pull_request.merged == true && inputs.dependent_branch == github.head_ref }}
        run: |
          git rebase --strategy-option theirs --onto origin/${{ inputs.main_branch }} ${{ inputs.dependent_branch }}
          git push origin ${{ inputs.dependent_branch }} --force

      - name: Rebase ${{ inputs.dependent_branch }}
        if: ${{ github.event.pull_request.merged == true && inputs.dependent_branch != github.head_ref }}
        continue-on-error: true
        run: |
          git rebase origin/${{ inputs.main_branch }}
          git push origin ${{ inputs.dependent_branch }} --force
